### PR TITLE
Update ES snapshot

### PR DESCRIPTION
**Pull request by arkid15r**
## Proposed change

Sync snapshot w/ https://github.com/vacanza/python-holidays/pull/1476 changes

## Type of change

- [ ] New country/market holidays support (thank you!)
- [ ] Supported country/market holidays update (calendar discrepancy fix, localization)
- [x] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] I've added references to all holidays information sources used in this PR
- [x] This PR is filed against `beta` branch of the repository
- [x] This PR doesn't contain any merge conflicts and has clean commit history
- [x] The code style looks good: `make pre-commit` command generates no changes
- [x] All tests pass locally: `make test`, `make tox` (we strongly encourage adding tests to your code)
- [x] The related [documentation][docs] has been added/updated (check off the box for free if no updates is required)

[contributing-guidelines]: https://github.com/vacanza/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/python-holidays/tree/beta/docs/source

### CODE REVIEW

**Comment by PPsyrius** [comment]
Just for future PRs, is there a way for contributors to update the relevant snapshot(s) by themselves? @arkid15r

**Comment by arkid15r** [comment]
> Just for future PRs, is there a way for contributors to update the relevant snapshot(s) by themselves? @arkid15r

That's a good question. You can update the snapshot by running `make snapshot` if that's available for you or just `scripts/generate_snapshots.py` manually. 

I'm still hesitant about adding snapshot update requirement as a part of regular contributor PRs. I don't want overcomplicate the process for new (and existing) contributors. I believe it can be done automatically later but in this case reviewers won't be able to see the "footprint" of holiday changes (if any). @KJhellico what's your opinion on this?

**Comment by KJhellico** [comment]
I agree that it's not yet practical to make updated snapshots required for PR, because it will be an additional challenge for new participants. So let's consider this as a desirable condition (like 100% tests coverage).

**Review by KJhellico — APPROVED** [review]
LGTM.

**Pull request merged**
