### PR TITLE
Add JULIAN_REVISED_CALENDAR calendar

### LINKED ISSUE #1378: Add REVISED_JULIAN_CALENDAR
Add REVISED_JULIAN_CALENDAR constant for Christian holidays of Eastern Orthodox countries that use [this calendar](https://en.wikipedia.org/wiki/Revised_Julian_calendar) (Bulgaria, Cyprus, Greece, Romania, from Sep 2023 - Ukraine).

### PR DESCRIPTION
**Pull request by KJhellico**
## Proposed change

Add JULIAN_REVISED_CALENDAR calendar constant (close #1378).

## Type of change

- [ ] New country/market holidays support (thank you!)
- [ ] Supported country/market holidays update (calendar discrepancy fix, localization)
- [x] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] This PR is filed against `beta` branch of the repository
- [x] This PR doesn't contain any merge conflicts and has clean commit history
- [x] The code style looks good: `make pre-commit`
- [x] All tests pass locally: `make test`, `make tox` (we strongly encourage adding tests to your code)
- [x] The related [documentation][docs] has been added/updated (check off the box for free if no updates is required)

[contributing-guidelines]: https://github.com/dr-prodigy/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/dr-prodigy/python-holidays/tree/beta/docs/source

### CODE REVIEW

**Review by arkid15r — COMMENTED** [review]
What's your opinion on using `JULIAN_REVISED_CALENDAR` instead?

**Comment by KJhellico** [comment]
It's based on [commonly used name](https://en.wikipedia.org/wiki/Revised_Julian_calendar), but it doesn't really matter . I've seen someone use MILANKOVIC for similar constant name. :)

**Comment by arkid15r** [comment]
> It's based on [commonly used name](https://en.wikipedia.org/wiki/Revised_Julian_calendar), but it doesn't really matter. I've seen someone use MILANKOVIC for similar constant name. :)

Yeah, I saw the origin details, just want to keep it closer to `julian_`. Let's rename it?

**Review by arkid15r — COMMENTED** [review]
That's a nice update. Had no idea it existed.

LGTM

**Pull request merged**
