### PR TITLE
Update Slovakia holidays

### PR DESCRIPTION
**Pull request by jose1711**
Fix missing space and improve spelling.

### CODE REVIEW

**Review by KJhellico — COMMENTED** [review]
@jose1711, thanks for your adjustments! Epiphany name should be definitely corrected. But according to [text of the law](https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/1993/241/), it's "sviatok svätého Cyrila a svätého Metoda".
Also need to make changes to tests and l10n files.

**Comment by jose1711** [comment]
> according to [text of the law](https://www.slov-lex.sk/pravne-predpisy/SK/ZZ/1993/241/), it's "sviatok svätého Cyrila a svätého Metoda". 

True, however in real life this is almost always shortened to "Sviatok svätého Cyrila a Metoda" or even a bit more: "Sviatok sv. Cyrila a Metoda". It is presumed that both were saints thus seeing "Sviatok Cyrila a Metoda" is not uncommon too.

**Comment by KJhellico** [comment]
Yes, I see. But if we have official sources, we try to rely on them.

**Comment by jose1711** [comment]
> Yes, I see. But if we have official sources, we try to rely on them.

Fair enough - will change that. Also please note that the English translation (`en_US/LC_MESSAGES/SK.po`) is currently in a contracted form: "St. Cyril and Methodius Day".

**Comment by arkid15r** [comment]
Thanks for the contribution @jose1711!

> Fair enough - will change that.

We highly appreciate the real users insights and I would totally understand if you found keeping the law name somewhat frustrating. 


> Also please note that the English translation (`en_US/LC_MESSAGES/SK.po`) is currently in a contracted form: "St. Cyril and Methodius Day".

Is it something you'd like to take care of within this PR?

**Comment by jose1711** [comment]
> Thanks for the contribution @jose1711!
> 
> > Fair enough - will change that.
> 
> We highly appreciate the real users insights and I would totally understand if you found keeping the law name somewhat frustrating.

:+1: 

> 
> > Also please note that the English translation (`en_US/LC_MESSAGES/SK.po`) is currently in a contracted form: "St. Cyril and Methodius Day".
> 
> Is it something you'd like to take care of within this PR?

No as this is not exactly my area.

**Review by arkid15r — APPROVED** [review]
Merging this PR, thanks for fixing the name!

**Pull request merged**
