### PR TITLE
Update Malaysia holidays

### PR DESCRIPTION
**Pull request by shahonseven**
## Proposed change

Update Malaysia holidays

## Type of change

- [ ] New country/market holidays support (thank you!)
- [x] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] I've run `make pre-commit`, it didn't generate any changes
- [x] I've run `make test`, all tests passed locally

[contributing-guidelines]: https://github.com/vacanza/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/python-holidays/tree/beta/docs/source

### CODE REVIEW

**Comment by KJhellico** [comment]
@shahonseven, thank you for this update. Are there any official sources?

**Comment by PPsyrius** [comment]
> @shahonseven, thank you for this update. Are there any official sources?

I'm going to assume that https://www.kabinet.gov.my/bkpp/pdf/hari_kelepasan_am/hka_2024.pdf was used here though that one is inaccessible from Thailand at the moment.

Going by a [proxy calendar site](https://publicholidays.com.my/2024-dates/) which refers to that link though - I found some discrepancies for `HIJRI_NEW_YEAR_DATES` as that should instead be on Jul 7, with an observance placed on Jul 8:
image

**Comment by shahonseven** [comment]
> > @shahonseven, thank you for this update. Are there any official sources?
> 
> I'm going to assume that https://www.kabinet.gov.my/bkpp/pdf/hari_kelepasan_am/hka_2024.pdf was used here though that one is inaccessible from Thailand at the moment.
> 
> Going by a [proxy calendar site](https://publicholidays.com.my/2024-dates/) which refers to that link though - I found some discrepancies for `HIJRI_NEW_YEAR_DATES` as that should instead be on Jul 7, with an observance placed on Jul 8: image

Ah sorry it should be 7th, my mistake

**Review by KJhellico — DISMISSED** [review]
LGTM. We also need to update snapshots. And it would be good to update tests...

**Comment by arkid15r** [comment]
> LGTM. We also need to update snapshots. And it would be good to update tests...

I've sorted this out. PTAL.

**Review by KJhellico — APPROVED** [review]
LGTM 🇲🇾

**Pull request merged**
