### PR TITLE
Update README.rst: clarify subdivisions ISO 3166-2 clause

### PR DESCRIPTION
**Pull request by mborsetti**
## Proposed change

Clarified in documentation the part of the ISO 3166-2 code we use to identify subdivisions.

BTW, this form doesn't even contemplate documentation changes! 😭

## Type of change

- [ ] New country/market holidays support (thank you!)
- [ ] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency upgrade (version update)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] This PR is filed against `beta` branch of the repository
- [x] This PR doesn't contain any merge conflicts and has clean commit history
- [ ] The code style looks good (`make pre-commit`)
- [ ] I've added tests to verify that the new code works and all tests pass locally (`make test`, `make tox`)
- [X] The related [documentation][docs] has been added/updated (check off the box for free if no updates is required)

[contributing-guidelines]: https://github.com/dr-prodigy/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/dr-prodigy/python-holidays/tree/beta/docs/source

### CODE REVIEW

**Comment by PPsyrius** [comment]
@mborsetti You might want to change the PR from merging into `master` to `beta` instead IMO

**Comment by mborsetti** [comment]
> @mborsetti You might want to change the PR from merging into `master` to `beta` instead IMO

Absolutely, lol. Thanks for catching this.

**Review by arkid15r — COMMENTED** [review]
Hey Mike, thanks for updating this!

I guess you still need to go over all checklist items to make sure the PR is ready for review.
I'll also make sure to update the PR template based on your comment

**Comment by mborsetti** [comment]
> Hey Mike, thanks for updating this!
> 
> I guess you still need to go over all checklist items to make sure the PR is ready for review. I'll also make sure to update the PR template based on your comment

Yeah, I did the edit on www.github.com and I guess it's not that easy to do it from here.

**Comment by PPsyrius** [comment]
@mborsetti I've created a PR to make this PR works for the latest release, cheers :)

**Pull request closed without merging**
