### PR TITLE
add get next workday support.

### PR DESCRIPTION
**Pull request by davidleon**
## Proposed change

Your PR description goes here.

## Type of change

- [ ] New country/market holidays support (thank you!)
- [ ] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [ ] I've followed the [contributing guidelines][contributing-guidelines]
- [ ] I've run `make pre-commit`, it didn't generate any changes
- [ ] I've run `make test`, all tests passed locally

[contributing-guidelines]: https://github.com/vacanza/python-holidays/blob/dev/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/python-holidays/tree/dev/docs/source

### CODE REVIEW

**Comment by KJhellico** [comment]
@davidleon, thank you for your great idea! 👍 Actually, substituted holidays structure was planned considering possibility of defining working days. But I have a some remarks about your implementation.

1. I don't see a need to keep name for the date (especially the name that was created for **day of holiday** - `"Day off (substituted from …)"`). So we can use just `Set[date]` for `workdayofweekend`.
2. `get_next_workday()` method should be moved to `HolidayBase`.
3. Seems logical to create `is_workday()` method also.

**Review by arkid15r — COMMENTED** [review]
Hi @davidleon,
could you make your code with the pre-commit rules?

**Comment by arkid15r** [comment]
It's just a friendly reminder to address the pre-commit issue before we could start actual code review.

Thank you!

**Comment by KJhellico** [comment]
Implemented in #1773.

**Pull request closed without merging**
