### PR TITLE
Add `UNOFFICIAL` category for the United States.

### LINKED ISSUE #1643: Additional Holidays
Valentine's Day (02/14), St. Patrick's Day (03/17), Halloween (10/31) and Election Day (First Tues every 4 years ((this year is 11/05)) ). Could you please add these to the US Holiday Calendar?

### PR DESCRIPTION
**Pull request by PPsyrius**
## Proposed change

This PR implements additional holidays (marked as `UNOFFICIAL` category), which includes:
- __Groundhog Day__ (FEB, 2).
- __Valentine's Day__ (FEB, 14) from 1847 onwards.
- __St. Patrick's Day__ (MAR, 17).
- __Halloween__ (OCT, 31).
- (US Presidential) __Election Day__ (Tuesday next after the 1st Monday in NOV) from 1848 onwards.

Closes #1643 .

## Type of change

- [ ] New country/market holidays support (thank you!)
- [x] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] I've run `make pre-commit`, it didn't generate any changes
- [x] I've run `make test`, all tests passed locally

[contributing-guidelines]: https://github.com/vacanza/python-holidays/blob/beta/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/python-holidays/tree/beta/docs/source

### CODE REVIEW

**Comment by PPsyrius** [comment]
Note: due to the current United States implementation, `_populate_subdiv_holidays(self)` will likely throw additional holidays into all `test_[category_name]_holiday`. I did try changing the former to `_populate_subdiv_public_holidays(self)`, but that doesn't work either, as the current syntactic sugar interprets `public` as a SUBDIV name.

**Comment by KJhellico** [comment]
While we don't have NON_PUBLIC subdiv holidays, we can just add
```
        if PUBLIC not in self.categories:
            return None
```
to the beginning of `_populate_subdiv_holidays()`.

When such holidays appear, we should change it to
```
       if PUBLIC in self.categories:
            # MLK Day ...
```

**Comment by PPsyrius** [comment]
> Happy Groundhog Day! 🎉😉

It turns out from some checks they do celebrate this in Hawaii, too, instead of just the Continental U.S. huh, even if they didn't have any groundhogs there 👀

**Review by KJhellico — COMMENTED** [review]
LGTM. This category (NON PUBLIC) opens up a very wide field of activity for us... ;)

**Comment by PPsyrius** [comment]
If there any additional changes required for this PR? 👀

**Comment by arkid15r** [comment]
> If there any additional changes required for this PR? 👀

No, not really. I was just thinking about `NON_PUBLIC` vs `UNOFFICIAL` naming. To me non-public is closer to private than unofficial. I know I kind of approved it in the issue discussion earlier. @KJhellico what's your opinion?

**Comment by KJhellico** [comment]
I also like `UNOFFICIAL` better. :)

**Comment by PPsyrius** [comment]
I think my bad habits of `git pull --rebase` then `git push -f` for my own private repos might have accidentally been used here... 💀 

Anyway, I've now switched all instances of `NON_PUBLIC` to `UNOFFICIAL` now. @KJhellico @arkid15r

**Review by arkid15r — APPROVED** [review]
LGTM

**Comment by mborsetti** [comment]
Apologies, thanks for all the work on this library and this looks neat, but is there any documentation on how to use it?  

I don't seem to find instructions on how to request "categories" in the [documentation](https://python-holidays.readthedocs.io/en/latest/index.html), yet I presume that any changes would have to be thoroughly documented to the user before a PR is merged. Where should I look?

Also, what is the definition and criteria for `UNOFFICIAL` (this seems to be missing from the documentation as well)? Would [National Fruitcake Toss Day](https://simplified.com/social-media-holidays/fruitcake-toss-day) be included in this library or not? If so, why?

**Comment by PPsyrius** [comment]
@mborsetti  I'm pretty sure they're listed in https://python-holidays.readthedocs.io/en/latest/api.html#holidays.holiday_base.HolidayBase

So, for example, calling up the Californian-specific list for 2024 with `UNOFFICIAL` list included would be 
```python
holidays.country_holidays("US", subdiv="CA", years=2024, categories=("public","unofficial",))
```
We might want to update `categories=None` to `categories=PUBLIC` for default ones as listed in https://github.com/vacanza/python-holidays/blob/dev/holidays/holiday_base.py unless I misunderstood our own codebase @KJhellico @arkid15r 

___

In terms of criteria, there are a bunch of similarities with the existing `WORKDAY` category - although those are officially observed by their respective governments, for which "Cinco de Mayo" would've fallen in this category due to its [US Congress concurrent resolution status](https://www.congress.gov/bill/109th-congress/house-concurrent-resolution/44/text).

`UNOFFICIAL`, on the other hand, are popular days that are widely observed by citizens of a particular jurisdiction with no official observance - for which "Valentine's Day", "Groundhog Day", and "Halloween" perfectly fit.

Unless "National Fruitcakes Toss Day" is celebrated with some events being held for it, I don't think it belongs in this category except for perhaps [Manitou Springs, Colorado](https://manitousprings.org/events/fruitcake-toss/) if we ever get to add that subdivision in once #1713 is implemented.

**Comment by arkid15r** [comment]
Hey Mike, long time no see!

It's great you're still keeping an eye on the PH. I appreciate your reminder regarding keeping the docs up to date (which is not always the case). 

Let's look into your concerns in details:

> I don't seem to find instructions on how to request "categories"

The usage of categories mentioned [here](https://python-holidays.readthedocs.io/en/latest/index.html#available-countries) and in the [Holiday categories support](https://python-holidays.readthedocs.io/en/latest/examples.html#holiday-categories-support) section. All supported categories specified on [per entity basis](https://python-holidays.readthedocs.io/en/latest/search.html?q=categories&check_keywords=yes&area=default) and listed in the [Available Countries](https://python-holidays.readthedocs.io/en/latest/index.html#available-countries) table (Supported Categories column).

What documentation is missing is description of each category (I'll create an issue to address that). This leads us to your next concern
>what is the definition and criteria for UNOFFICIAL

As there is no standard for holiday categories I trust other fellow contributors/maintainer with their choice unless I clearly notice something is not fit. Normally we resolve this kind of concerns during code reviews or in issues.

My general observation is that PH could use a better implemented/documented code ratio. Neither of the current maintainers are native English speakers. But if you want to blame somebody for that -- it'd be me. I'm responsible for this level of documentation quality (normally I review and approve every PR merged into dev/main branch -- btw, we moved to the new branch naming recently!). You can see @PPsyrius's response above with his idea of `UNOFFICIAL` hoiiday meaning. I can't agree more that each category purpose should be properly documented.

I also think it's worth to mention that I've started planning PH v1 [roadmap](https://github.com/vacanza/python-holidays/issues/1649) recently. It has a separate issue for better documentation. If you have any suggestions/ideas please contribute.

**Comment by arkid15r** [comment]
> We might want to update `categories=None` to `categories=PUBLIC` for default ones as listed in https://github.com/vacanza/python-holidays/blob/dev/holidays/holiday_base.py unless I misunderstood our own codebase @KJhellico @arkid15r

It's handled [here](https://github.com/vacanza/python-holidays/blob/84a9277763ca65700ed7d91506ff333df0625a4e/holidays/holiday_base.py#L298). The [default](https://github.com/vacanza/python-holidays/blob/84a9277763ca65700ed7d91506ff333df0625a4e/holidays/holiday_base.py#L232) category is `PUBLIC` and designed to be modifiable for better flexibility.

**Comment by mborsetti** [comment]
Hey Arkadii,

Thanks for your response, and great leadership!

I do get notices of new releases and when I have time check in on all the great improvements; wonderful job, I can't believe how many countries/subdivisions are supported now!

> I also think it's worth to mention that I've started planning PH v1 [roadmap](https://github.com/vacanza/python-holidays/issues/1649) recently. 

Wow, wonderful to see; the API does indeed need rethinking IMHO.  I see if I have time to do a deeper dive.

**Comment by arkid15r** [comment]
> I do get notices of new releases and when I have time check in on all the great improvements; wonderful job, I can't believe how many countries/subdivisions are supported now!

That's right! A lot of people contributed to PH's success. However, personally I'm really proud of the **quality** of the data provided by PH. @KJhellico and @PPsyrius have been doing amazing work on hunting down every single holiday in their contributions.

**Pull request merged**
