### PR TITLE
Add Samoa holidays

### PR DESCRIPTION
**Pull request by kasya**
## Proposed change

Add Samoa holidays

## Type of change

- [x] New country/market holidays support (thank you!)
- [ ] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/pin/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] I've run `make pre-commit`, it didn't generate any changes
- [x] I've run `make test`, all tests passed locally

[contributing-guidelines]: https://github.com/vacanza/python-holidays/blob/dev/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/python-holidays/tree/dev/docs/source

### CODE REVIEW

**Review by KJhellico — COMMENTED** [review]
@kasya , it's great: 150 countries, a significant number! 👍
Please take a look at a few suggestions. :)

**Comment by kasya** [comment]
> @kasya , it's great: 150 countries, a significant number! 👍 Please take a look at a few suggestions. :)

@KJhellico Thanks for the review! 👍🏼

**Review by KJhellico — APPROVED** [review]
LGTM!

**Review by arkid15r — COMMENTED** [review]
Thanks you @kasya!

@KJhellico is right -- 150 countries is a huge milestone! We move slowly but we make a good progress!

This LGTM, just needs `make snapshot` update before the merge.

**Review by arkid15r — APPROVED** [review]

**Pull request merged**
