### PR TITLE
Update saudi_arabia.py

### PR DESCRIPTION
**Pull request by Saad-nvd**
Added weekend = {FRI, SAT}

## Proposed change

Updated weekend = {FRI, SAT}

## Type of change

- [ ] New country/market holidays support (thank you!)
- [x] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] I've run `make pre-commit`, it didn't generate any changes
- [x] I've run `make test`, all tests passed locally

[contributing-guidelines]: https://github.com/vacanza/python-holidays/blob/dev/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/python-holidays/tree/dev/docs/source

### CODE REVIEW

**Review by arkid15r — COMMENTED** [review]
Hi @Saad-nvd,
Thanks for the PR!

It seems we already handle this via `SaudiArabia::_populate_public_holidays()`

**Comment by arkid15r** [comment]
Closing this as it's been taken care of [here](https://github.com/vacanza/python-holidays/blob/8d821de82249554be3c9930a46211d29e6f320a1/holidays/countries/saudi_arabia.py#L79)

Thank you, @Saad-nvd!

**Comment by Saad-nvd** [comment]
The below returns wrong weekend for Saudi Arabia:
            weekend = holidays.country_holidays('SA').weekend
See attached snippet:
SA Weekend

**Comment by Saad-nvd** [comment]
Please ignore my previous comment as I know the problem.

**Pull request closed without merging**
