### PR TITLE
Move to `holidays` from `python-holidays`

### PR DESCRIPTION
**Pull request by arkid15r**
Make it consistent for GitHub, PyPI, and Read the Docs

## Proposed change

Prepare changes for the following naming standardization.

## Type of change

- [ ] New country/market holidays support (thank you!)
- [ ] Supported country/market holidays update (calendar discrepancy fix, localization)
- [ ] Existing code/documentation/test/process quality improvement (best practice, cleanup, refactoring, optimization)
- [ ] Dependency update (version deprecation/pin/upgrade)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Breaking change (a code change causing existing functionality to break)
- [ ] New feature (new python-holidays functionality in general)

## Checklist

- [x] I've followed the [contributing guidelines][contributing-guidelines]
- [x] I've run `make pre-commit`, it didn't generate any changes
- [x] I've run `make test`, all tests passed locally

[contributing-guidelines]: https://github.com/vacanza/python-holidays/blob/dev/CONTRIBUTING.rst
[docs]: https://github.com/vacanza/python-holidays/tree/dev/docs/source

### CODE REVIEW

**Review by KJhellico — DISMISSED** [review]
LGTM!

**Review by PPsyrius — DISMISSED** [review]

**Comment by PPsyrius** [comment]
LGTM 🌐

**Review by KJhellico — APPROVED** [review]
LGTM!

**Review by PPsyrius — APPROVED** [review]
I'm going to assume you got all the files, LGTM 🌐

**Comment by arkid15r** [comment]
> I'm going to assume you got all the files, LGTM 🌐

Hopefully 🤞

If you notice something you know what to do :)

**Comment by PPsyrius** [comment]
@arkid15r I think we might've forgotten to update codecov after we implemented the repo name change.

**Comment by arkid15r** [comment]
> @arkid15r I think we might've forgotten to update codecov after we implemented the repo name change.

It looks like it's okay now. Let's monitor it for a bit more.

**Pull request merged**
